/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactsContactIdImport } from './routes/contacts.$contactId'

// Create/Update Routes

const ContactsContactIdRoute = ContactsContactIdImport.update({
  id: '/contacts/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contacts/$contactId': {
      id: '/contacts/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof ContactsContactIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/contacts/$contactId': typeof ContactsContactIdRoute
}

export interface FileRoutesByTo {
  '/contacts/$contactId': typeof ContactsContactIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/contacts/$contactId': typeof ContactsContactIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/contacts/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to: '/contacts/$contactId'
  id: '__root__' | '/contacts/$contactId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ContactsContactIdRoute: typeof ContactsContactIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  ContactsContactIdRoute: ContactsContactIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/contacts/$contactId"
      ]
    },
    "/contacts/$contactId": {
      "filePath": "contacts.$contactId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
